# Generated by Django 3.2.9 on 2021-11-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='private_key',
        ),
    ]
