# Generated by Django 3.2.9 on 2021-12-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bets',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
