# Generated by Django 3.2.9 on 2021-12-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_bets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bets',
            field=models.IntegerField(default=0),
        ),
    ]
