# Generated by Django 3.2.9 on 2021-12-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_bets'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
