# Generated by Django 3.2.9 on 2021-12-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_currentbet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentbet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
